apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "denty.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "denty.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "denty.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "denty.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "denty.fullname" . }}-config
            - secretRef:
                name: {{ include "denty.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
