apiVersion: v1
kind: Secret
metadata:
  name: {{ include "denty.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "denty.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
