apiVersion: v1
kind: Service
metadata:
  name: {{ include "denty.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "denty.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "denty.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
