apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: denty
  namespace: denty
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - denty.es
        - www.denty.es
      secretName: denty-tls
  rules:
    - host: denty.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: denty
                port:
                  number: 80
    - host: www.denty.es
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: denty
                port:
                  number: 80
