# Staging overrides
replicaCount: 1

ingress:
  hosts:
    - host: staging.denty.es
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: denty-staging-tls
      hosts:
        - staging.denty.es

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi
